```yaml
title: Suspicious OAuth Application Consent Grant Following Service Principal Creation
id:
status: draft
description: Detects a high-risk OAuth application consent grant to a newly created service principal, a technique associated with threat actor Storm-0558 for persistent access to cloud environments, as referenced in the Microsoft negligence probe.
references:
  - https://thehackernews.com/2025/09/senator-wyden-urges-ftc-to-probe.html
  - https://www.microsoft.com/en-us/security/blog/2023/09/06/storm-0558-attacks-with-forged-authentication-tokens-targeting-cloud-infrastructure/
  - https://learn.microsoft.com/en-us/azure/active-directory/develop/consent-framework
author:
date: 2024-06-22
logsource:
  category: cloud
  product: microsoft
  service: azuread
detection:
  selection:
    operationName: "Consent to application"
    Result: "success"
    TargetResources|contains: "ServicePrincipal"
  filter:
    InitiatedBy|user|userPrincipalName|endswith:
      - "@microsoft.com"
      - "@microsoftonline.com"
  timeframe: 24h
  condition: selection and not filter
falsepositives:
  - Legitimate administrative activity from Microsoft's own domains. This rule filters out common Microsoft service accounts, but any internal admin accounts that perform regular service principal management should be added to the exclusion list. Tuning is required for the specific environment.
level: high
tags:
  - attack.persistence
  - attack.t1136.003
  - attack.t1098.002
  - attack.initial_access
  - cef.cloud
  - cloud.azure
```