yaml
title: Suspicious OAuth Application Grant for Known Malicious Browser Extension
id:
status: draft
description: Detects the granting of OAuth permissions to a known malicious browser extension, as used in campaigns to hijack Meta Business accounts via fake Madgicx Plus and SocialMetrics extensions.
references:
  - https://thehackernews.com/2025/09/fake-madgicx-plus-and-socialmetrics.html
author:
date: 2024/09/21
logsource:
  category: authentication
  product: google_workspace
  service: oauth
detection:
  selection:
    event.action: AUTHORIZE
    application.name|contains:
      - 'Madgicx Plus'
      - 'SocialMetrics'
  condition: selection
falsepositives:
  - Manual verification is required. Legitimate extensions with similar names may trigger this alert. Administrators should review the application's publisher and requested permissions.
level: high
tags:
  - attack.initial_access
  - attack.t1658  # OAuth Abuse
